# Generated by Django 5.2 on 2025-05-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
